import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Toaster } from '../components/ui/sonner';
import { ReactNode } from 'react';
import Header from 'app/components/Header/Header';
import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'], weight: ['400', '800'] });

export const metadata: Metadata = {
  title: 'Yap Store',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
      </body>
      <Toaster />
    </html>
  );
}
